### ISSUE TITLE
Preview window over navbar in Homepage

### ISSUE THREAD

**Issue by Barissa-Imran** [chakra-ui/chakra-ui-docs#1210]
### Description

The preview window appears on top of the navbar on scroll. as seen in the image (right)

![image](https://user-images.githubusercontent.com/74467681/200199595-7394f4ea-1ade-4bf2-a7ae-9603fb438b7f.png)

### Link to Reproduction

https://chakra-ui.com/

### Steps to reproduce

1. Go to 'https://chakra-ui.com/'
2. Scroll down to 'Less code. More speed section'

### Chakra UI Version

2.3.7

### Browser

Google chrome Version 107.0.5304.88

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I don't know if this was meant to be so or if it's a bug

**Comment by nikolovlazar** [comment]
Thanks for opening this issue @Barissa-Imran. This issue happens only while the sandpack component is loading, but it clears out afterwards, so I wouldn't put too much priority on it.

**Comment by adrianmarinwork** [comment]
Hello, by inspecting the browser and looking for the component I have found out where the problem is coming from, as expected it's related to the `z-index` css attribute, if you remove the attribute or change the value of it in the class that appears in the screenshoot that I append to this message it fixes the issue.](url)
![Captura](https://user-images.githubusercontent.com/118568289/202859910-f1f03c03-d6eb-48e6-bc27-1fb85f39cfd9.PNG)
