### ISSUE TITLE
Double entries of organisation and individual sponsors on landing page

### ISSUE THREAD

**Issue by m4x3d** [chakra-ui/chakra-ui-docs#330]
### Description

On the landing page are multiple entries doubled on the organization and individual sponsors section, see my screenshot below. After a bit of investigation I found out that in the [.all-sponsorsrc](https://github.com/chakra-ui/chakra-ui-docs/blob/main/.all-sponsorsrc) are people/organizations doubled with different `MemberIds`, e.g.:
Organizations:
- Shogun: 167894 and 189810
- Touchless: 98173 and 98175

Individuals:
- Segun Adebayo: 51659 and 179387
- Tim Kolberger: 158176 and 175726
- Javier Alaves: 219561 and 224250

Also organization without a website which are on the landing page (a tag without href):
- Chakra UI Pro -> obviously: https://pro.chakra-ui.com
- Touchless -> https://www.touchless.inc/

I'm not sure if it is enough to wipe out that doubled entries and add missing website-URLs in the file or there are other things to do. If this solves the problem once and for all just give me a 'go' or assign me then I will clean it up, 'hard work' is already done by creating this ticket.

![Screenshot from 2022-02-16 22-04-52](https://user-images.githubusercontent.com/44474134/154357338-3e755851-74f6-4277-807a-bb86d421dcd5.png)

**Comment by TylerAPfledderer** [comment]
Hey @m4x3d!

I stumbled across this issue and figure I would help you out with observations if you haven't seen it yet. 😄

The `.all-sponsorsrc` file is generated via the `scripts/avatars.ts` file. It appears that the issue might come from the JSON data being fetched from the Open Collective: https://opencollective.com/chakra-ui/members/all.json

For example, with the two Shogun entries, they reference two different profiles: [Shogun](https://opencollective.com/shogun1) and [Shogun Labs, INC.](https://opencollective.com/shogun)

However, with the two Touchless entries, one of them includes an additional `tier` property. 🤔

With the two entries of Segun Adebayo, one has the property `role` set to `ADMIN` and the other set to `CONTRIBUTOR`

Would this truly be an issue within the Open Collective data being fetched? It would seem that additional scripting in `avatars.ts` might not necessarily be the best way to go because of the first example.

**Comment by nikolovlazar** [comment]
@TylerAPfledderer I think we can skip an entry if it already exists, regardless of the differences in properties. We can use the profile link to check if the entry already exists. In case of Shogun, I guess we can leave it because they've donated from 2 different accounts. But every other duplicate will be eliminated.

**Comment by m4x3d** [comment]
Thanks for your feedback @TylerAPfledderer and @nikolovlazar!
I will create a PR in a few minutes.
