### ISSUE TITLE
Broken link in Community examples on Global Styles features

### ISSUE THREAD

**Issue by aroyan** [chakra-ui/chakra-ui-docs#369]
### Description

When I open the link for [Community examples](https://chakra-ui.com/docs/features/global-styles#community-examples) from [Global Styles](https://chakra-ui.com/docs/features/global-styles) feature, I expected to open the example of [the project](https://git.habd.as/comfusion/gatsby-starter-i18n-react-i18next/src/branch/master/src/utils/theme.tsx) that using Global Styles feature but it seems that the link is broken.

**Comment by m4x3d** [comment]
Hey @aroyan, thanks for opening that issue! :smiley: 

Unfortunately it looks like the whole domain habd.as from that repo is down and also the the GitHub user 'Josh Habdas' who seems to be the owner of that repo and domain is deleted like you can see in this history: https://github.com/boletindigital/blog/commits/master

@noobinthisgame @nikolovlazar 
Im not sure if we especially need a external repo linked in here. So I guess it is a better approach to extend the example on the page if needed. But tbh I do not think it is necessary either, so that we can remove that whole section 'community examples'. Let me know what you think we should do here.

**Comment by nikolovlazar** [comment]
Yes, we can remove the Community Examples section.
