### ISSUE TITLE
Search -> FAQ -> Is there a Datepicker leads to 404

### ISSUE THREAD

**Issue by Patrick-Ullrich** [chakra-ui/chakra-ui-docs#449]
### Subject

Search

### Description

When searching "Is there a Datepicker in Chakra UI?" you will find an entry in the search but when clicking on the entry you will end on a 404.

https://chakra-ui.com/faq/index#is-there-a-datepicker-in-chakra-ui

<img width="694" alt="Screen Shot 2022-03-18 at 3 49 56 PM" src="https://user-images.githubusercontent.com/6193042/159094257-2e086ad7-aa1c-4c00-b57a-1d6ce72c21a9.png">
<img width="642" alt="Screen Shot 2022-03-18 at 3 50 41 PM" src="https://user-images.githubusercontent.com/6193042/159094321-4dbd558b-adb1-4724-a5ca-b7c54c110ee3.png">

I assume we either want to remove the entry or link it correctly if there is a document for this.

**Comment by TylerAPfledderer** [comment]
Hey @Patrick-Ullrich! Thank for the callout. 😁

I found an issue in the [`scripts/get-search-meta`](https://github.com/chakra-ui/chakra-ui-docs/blob/main/scripts/get-search-meta.ts#L32-L39) where the filepaths ending in `index.*` were being added to the search-meta with `index` still present. This is because of Windows (at least for me!) in how it returns file strings with backslashes instead of forward slashes, and it was impacting the effectiveness of some of the scripting when contributors update `search-meta.json` in future pull requests.

i.e. Me when contribute and I use Windows! 🤦‍♂️

The referenced pull request should resolve this issue along with one other page.

**Comment by nikolovlazar** [comment]
That's exactly right @TylerAPfledderer! In the meantime, I've regenerated the search meta and pushed it to fix this issue right away, while your PR will make the fix permanent.
