### ISSUE TITLE
docs(alert): Alerts examples responsiveness issues

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#505]
Some of the examples in the [Alert page](https://chakra-ui.com/docs/components/feedback/alert) have issues with responsiveness:
<img width="815" alt="CleanShot 2022-04-05 at 20 31 13@2x" src="https://user-images.githubusercontent.com/5396211/161825373-858b7210-d997-4d17-9044-f7368e437670.png">
<img width="793" alt="CleanShot 2022-04-05 at 20 32 09@2x" src="https://user-images.githubusercontent.com/5396211/161825393-54c44417-4b2c-4f2f-aee9-0df46ec7484a.png">

Possibly related to #496

**Comment by TylerAPfledderer** [comment]
Hey @nikolovlazar! Since that was my doing, you can assign it to me. I was looking to still survey some of these examples to see if they should be updated because of the overflow fix.

**Comment by TylerAPfledderer** [comment]
@noobinthisgame / @nikolovlazar So the `whiteSpace: pre` I applied to `LiveCodePreview` is the primary culprit here. I could remove it entirely, or resort to say `normal`.

At 375px mobile width, the first Alert example with now render like this:
![image](https://user-images.githubusercontent.com/65234762/161974787-5a4e9507-f06a-4433-b243-6602e31b9fc2.png)

However, in the [Form Control Sample Radio Group](https://chakra-ui.com/docs/components/form/form-control#sample-usage-for-a-radio-or-checkbox-group) the last radio will now look like this:
![image](https://user-images.githubusercontent.com/65234762/161975143-d20e3493-49c0-41fd-b175-25d4c1a43ee7.png)

Where should the importance be placed here? This is clearly a conflict in base styles of unrelated components in how they are handled here in the preview container. Would the Alert examples take priority because there is a higher visual impact in the issue and that the `Alert` component has a base style of `overflow: hidden`?

**Comment by TylerAPfledderer** [comment]
@jacobhq this is a part of #496, because there were other examples overflowing the preview container, so `overflow:auto` was applied to contain the previews.

Removing `whiteSpace: pre` will also fix the example you provided, because that prop was added with the overflow in hopes that it would simply maintain the original space in the desktop view. Unfortunately these side effects were overlooked.

**Comment by TylerAPfledderer** [comment]
However, there are still some examples that would need to be addressed because of the overflow applied, such as some text content being compressed. (that was my primary reason for adding `whiteSpace`)
