### ISSUE TITLE
Show major companies using Chakra UI on landing page

### ISSUE THREAD

**Issue by ilindaniel** [chakra-ui/chakra-ui-docs#609]
### Subject

Landing page

### Description

Some major companies like [StockX](https://stockx.com/), [Bitwarden](https://bitwarden.com/) and [Crypto.com](https://crypto.com/price) are using Chakra UI in production. I feel like we could put a logo grid on the landing page.

Let me know if this is a valid feature request and I will start working on it.

![2022-05-16_01-40](https://user-images.githubusercontent.com/25451549/168499382-376e08c4-52e0-4d3e-a173-2f95c2f0e79d.png)

**Comment by TylerAPfledderer** [comment]
Hey @ilindaniel! That might be a good idea, because they are front-facing consumers of the product, since users of their sites can see what it looks like to use Chakra. This is different than companies who support the product, because they don't always use it on their main site, but for their own projects. 😄 

I'm curious: There is such a section just beneath the fold for "Supported and Backed By". Are you interested in adding this proposed section above that? And are you thinking of making this above the fold?

**Comment by segunadebayo** [comment]
The companies we mention in that section are companies that sponsor Chaka UI (in OpenCollective), not just companies that use Chakra UI. We'll consider your thoughts though.

We could also consider adding their websites to the showcase section, with their permission of course.
