### ISSUE TITLE
Changelog broken live preview

### ISSUE THREAD

**Issue by noobinthisgame** [chakra-ui/chakra-ui-docs#632]
### Description

![image](https://user-images.githubusercontent.com/21695702/169617884-a347f082-e095-4c8e-8630-753ec5c32154.png)

The autogenerated changelog code snippets try to show the component. We need to add live=false to the md.

**Comment by TylerAPfledderer** [comment]
I can take this!

Can also update the `CONTRIBUTING.md` file for any new contributors to say that they need to make sure this setting is included if they are to provide code snippets.

**Comment by noobinthisgame** [comment]
I think giving a hint in the `CONTRIBUTING.md` would be nice, otherwise we will have to fix this over and over

**Comment by segunadebayo** [comment]
@TylerAPfledderer thanks for jumping on this. Feel free to open a PR to update the `contributing.md` file (I wonder if people actually read this. lol)

A better way we could explore is to programmatically replace all bare ```jsx with ```jsx live=false for the changelog file

**Comment by TylerAPfledderer** [comment]
@TylerAPfledderer I certainly read it! 😄 

I was curious about that, and I will continue exploring that possibility.

Also, this issue is not completely resolved, as making updates to the changelog in the package did not automatically update the docsite page. Can the site be redeployed to regenerate that page, or should I go in and do manual fixes?
