### ISSUE TITLE
(i18n): some languages the "with speed" part might not be at the end of the sentence.

### ISSUE THREAD

**Issue by wattanx** [chakra-ui/chakra-ui-docs#86]
### Subject

HomePage

### Description

some languages the "with speed" part might not be at the end of the sentence.
The following is a translation into Japanese.
![image](https://user-images.githubusercontent.com/43837308/144053773-ed3a466c-ac5c-410b-bcc2-a14ac8a16cf1.png)

This needs to be dealt with using an i18n format.
(I took care of it with this commit, but it was changed before I knew it.)
https://github.com/chakra-ui/chakra-ui-docs/pull/37/commits/8aa447b1a05eb7c061386d86a5ffb3b2320cc241

**Comment by wattanx** [comment]
I would like to be in charge if there is no problem with a fix like this commit.
https://github.com/chakra-ui/chakra-ui-docs/commit/8aa447b1a05eb7c061386d86a5ffb3b2320cc241

**Comment by lazarnikolov94** [comment]
@wattanx we've put a brief pause on the Localization feature. Turns out the platform we planned on using cannot accommodate a project like ours. I plan on moving the translation process to the repo itself (no platforms, just simply using code and opening PRs), and I also plan on recording a simple onboarding video for any translator that would like to contribute. I'll let you know when and how we can proceed with the translation.

**Comment by nikolovlazar** [comment]
Closing translation issues for now.
