### ISSUE TITLE
More details about props

### ISSUE THREAD

**Issue by j-castellanos** [chakra-ui/chakra-ui-docs#917]
### Subject

component props

### Description

I'm having a difficult time understanding what values to pass in for many of the props.

For instance with `Grid` I don't see anywhere where there is a list of values for `templateColumns`. In the example I see `repeat(3, 1fr)` but no description of what that means.

For `IconButton` there is color scheme, which I guess the only way to override is to extend the theme or use a complicated box to customize. I don't see anywhere where is tells you 500 is background, 600 is hover, 700, is while clicked.

It's difficult to get started and convert components without more details of how to use chakra. Am I missing docs somewhere?

**Comment by TylerAPfledderer** [comment]
Hey @j-castellanos! Great to see your interest in using the package.

For each of the component pages, you should find a tab at the top of the page called `Props` (assuming that you are viewing the site for the most latest version of Chakra, V2.

For the `Grid` component, you will find the `templateColumns` component there.

I would keep in mind that even though the docs try to be as explicit as necessary, it's possible that you might not see detail for all props because some used in the example are not specific to a component. For example `templateColumns` is a common style property for CSS Grid as not a name specific to Chakra.

You should view the Props tab for Grid here: https://chakra-ui.com/docs/components/grid/props

I hope this helps! 😄

**Comment by j-castellanos** [comment]
@TylerAPfledderer ah got it, I haven't needed to use normal css in a long time so wasn't aware of the grid-template-columns css syntax. It would be nice though it the props that are described as "shorthand for `some-prop`" link to that prop and that prop links to the documentation for the regular css. So when viewing `Grid` you see `templateColumns` which links to `gridTemplateColumns` which links to https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns

**Comment by TylerAPfledderer** [comment]
Closing issue, as the documentation provides as much detail as necessary to describe shorthand props in question.

Linking further details about a prop to an outside source is outside the scope of the package, unless the team would favor providing an external source for every single CSS prop, shorthand or otherwise. That is arguably excessive as basic knowledge of CSS is expected when using Chakra UI or any other package that involves CSS.
